development:
  adapter: postgresql
  database: dphBlog_develop
  username: darin
  password: marley12
  host: localhost
  encoding: UTF8
test:
  adapter: postgresql
  database: dphBlog_test
  username: darin
  password: marley12
  host: localhost
  encoding: UTF8
production:
  adapter: postgresql
  database: dphBlog_production
  username: darin
  password: marley12
  host: localhost
  encoding: UTF8
